#ifndef CONFIG_H
#define CONFIG_H

#include "pcb_config.h"

#define PIN_STATUS_LED 2
#define STATUS_LED_TOGGLE_MS 500U

#define SENSOR_SDA gSensorSda
#define SENSOR_SCL gSensorScl
#define SENSOR_UPDATE_INTERVAL_MS 10U
#define FUSION_BETA_NORMAL 0.4f

#define PIN_LEFT_A gPinLeftA
#define PIN_LEFT_B gPinLeftB
#define PIN_RIGHT_A gPinRightA
#define PIN_RIGHT_B gPinRightB
#define PWM_CH_LEFT 0
#define PWM_CH_RIGHT 1
#define PWM_FREQ 20000
#define PWM_BITS 8
#define PWM_MAX 255
#define MOTOR_CRUISE_STOP_BLANK_US 100

#define WEB_AP_CHANNEL 1
#define WEB_AP_MAX_CONNECTIONS 4
#define WEB_MANUAL_DEFAULT_PWM PWM_MAX
#define WEB_TURN_MOTOR_PWM ((PWM_MAX * 70 + 50) / 100)
#define WEB_MANUAL_WATCHDOG_MS 900U
#define WEB_CRUISE_TURN_STEP_DEG 15.0f

#define PIN_SERVO_LEFT_FOOT 1
#define PIN_SERVO_RIGHT_FOOT 0
#define PIN_SERVO_LEFT_HAND 10
#define PIN_SERVO_RIGHT_HAND 3
#define SERVO_COUNT 4
#define PWM_CH_SERVO_LEFT_FOOT 2
#define PWM_CH_SERVO_RIGHT_FOOT 3
#define PWM_CH_SERVO_LEFT_HAND 4
#define PWM_CH_SERVO_RIGHT_HAND 5
#define SERVO_FREQ 50
#define SERVO_BITS 14
#define SERVO_PULSE_MIN_US 500
#define SERVO_PULSE_MAX_US 2400
#define SERVO_POS_DEG_MAX 180

#define GAIT_LEFT_FOOT_CENTER 60
#define GAIT_LEFT_FOOT_AMPLITUDE 15
#define GAIT_RIGHT_FOOT_CENTER 100
#define GAIT_RIGHT_FOOT_AMPLITUDE 15
#define GAIT_LEFT_HAND_CENTER 55
#define GAIT_LEFT_HAND_AMPLITUDE 25
#define GAIT_RIGHT_HAND_CENTER 115
#define GAIT_RIGHT_HAND_AMPLITUDE 25

#define CRUISE_DEFAULT_BASE_SPEED 190
#define CRUISE_DEFAULT_TWIST_LEFT_MS 250U
#define CRUISE_DEFAULT_TWIST_RIGHT_MS 250U
#define CRUISE_INNER_RATIO_PCT 0U
#define CRUISE_INNER_PWM_OFFSET 30
#define CRUISE_SPEED_MIN 1
#define CRUISE_YAW_POLARITY 1
#define CRUISE_PID_KP 2.0f
#define CRUISE_PID_KI 0.8f
#define CRUISE_PID_KD 0.5f
#define CRUISE_PID_INT_MAX 500.0f
#define CRUISE_CORR_MAX 200

#endif
