[env:esp32c3-bare]
platform = espressif32@6.6.0
board = seeed_xiao_esp32c3
framework = arduino
board_build.flash_mode = dio
build_flags = -DCORE_DEBUG_LEVEL=0
lib_deps =
    lewisxhe/SensorLib@^0.4.1
    adafruit/Adafruit AHRS@^2.4.0
